#! /bin/sh
Num_Of_Param=$#

if (( $Num_Of_Param != 2 ))
then
	echo "Invalid number of arguments entered."
	exit 1
else
	if [ ! -e $1 ]
	then
		echo "Error: $1 does not exist"
		exit 2
	
	else
		./Micro $1 > $2	
	fi
fi

exit 0


